# Generated by Django 3.2.12 on 2022-04-08 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nr_index',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Index student number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='students_amount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Students amount for project'),
        ),
    ]
