# Generated by Django 3.2.13 on 2022-05-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220415_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='studentteam',
            options={'verbose_name': 'Students team', 'verbose_name_plural': 'Students teams'},
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo of company'),
        ),
        migrations.AddField(
            model_name='studentteam',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo of student team'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('company', 'Company'), ('leader', 'Leader'), ('student_leader', 'Student leader'), ('student', 'Student')], max_length=255, verbose_name='Account type'),
        ),
    ]
