# Generated by Django 3.2.13 on 2022-05-14 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220504_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Registration notes'),
        ),
        migrations.AddField(
            model_name='studentteam',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation time'),
            preserve_default=False,
        ),
    ]
