# Generated by Django 3.2.13 on 2022-05-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Average from studies grades'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='Email address'),
        ),
    ]
