# Generated by Django 3.2.13 on 2022-05-20 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220520_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentteam',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.company', verbose_name='Company that team belongs to'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name of company'),
        ),
        migrations.AlterField(
            model_name='studentteam',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name of team'),
        ),
    ]
