# Generated by Django 3.2.13 on 2022-05-14 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20220504_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
    ]
