# Generated by Django 3.2.13 on 2022-05-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20220514_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_dt'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_dt'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
