# Generated by Django 3.2.13 on 2022-05-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='Kropka-App1', max_length=255, verbose_name='Name of project')),
                ('project_logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Logo of project')),
                ('contact_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone number for contact')),
                ('registration_end', models.DateTimeField(blank=True, null=True, verbose_name='Registration end time')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
