# Generated by Django 3.2.13 on 2022-06-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='contact_email',
            field=models.CharField(blank=True, default='zespolkropka@gmail.com', max_length=255, null=True, verbose_name='Email address for contact'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='contact_phone',
            field=models.CharField(blank=True, default='696 969 696', max_length=32, null=True, verbose_name='Phone number for contact'),
        ),
    ]
